git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.cltone
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.epassport.certificates
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.epassport.datagroups
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.epassport.securemessaging
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.prove.eac2
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.prove.eidclient
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.prove.epa
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.prove.epareader
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.prove.epp
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.prove.is
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.prove.pace
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.simulator
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.simulator.applets.epa
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.globaltester.tlvmanipulator
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.osgi.remotecontrol
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.osgi.remotecontrol.soap
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.persosim.simulator
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.persosim.simulator.protocols.ca3
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.persosim.simulator.protocols.ps
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.poseidas
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/com.hjp.simulator
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/de.persosim.driver.connector
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/de.persosim.rcp
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/de.persosim.simulator
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/org.globaltester.base
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/org.globaltester.cryptoprovider
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/org.globaltester.logging
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/org.globaltester.logging.legacy
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/org.globaltester.parent
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/org.globaltester.testeditor
git clone ssh://git@tourmaline.intranet.hjp-consulting.com/org.globaltester.testmanager
