
git clone git@git.hjp-consulting.com:com.hjp.globaltester.cltone
git clone git@git.hjp-consulting.com:com.hjp.globaltester.epassport.certificates
git clone git@git.hjp-consulting.com:com.hjp.globaltester.epassport.datagroups
git clone git@git.hjp-consulting.com:com.hjp.globaltester.epassport.securemessaging
git clone git@git.hjp-consulting.com:com.hjp.globaltester.prove.eac2
git clone git@git.hjp-consulting.com:com.hjp.globaltester.prove.eidclient
git clone git@git.hjp-consulting.com:com.hjp.globaltester.prove.pace
git clone git@git.hjp-consulting.com:com.hjp.globaltester.simulator
git clone git@git.hjp-consulting.com:com.hjp.globaltester.simulator.applets.epa
git clone git@git.hjp-consulting.com:com.hjp.osgi.remotecontrol
git clone git@git.hjp-consulting.com:com.hjp.osgi.remotecontrol.soap
git clone git@git.hjp-consulting.com:com.hjp.persosim.simulator
git clone git@git.hjp-consulting.com:com.hjp.simulator
git clone git@git.hjp-consulting.com:de.persosim.driver.connector
git clone git@git.hjp-consulting.com:de.persosim.simulator
git clone git@git.hjp-consulting.com:org.globaltester.base
git clone git@git.hjp-consulting.com:org.globaltester.cryptoprovider
git clone git@git.hjp-consulting.com:org.globaltester.logging
git clone git@git.hjp-consulting.com:org.globaltester.logging.legacy
git clone git@git.hjp-consulting.com:org.globaltester.parent
git clone git@git.hjp-consulting.com:org.globaltester.testeditor
git clone git@git.hjp-consulting.com:org.globaltester.testmanager
