git clone git@git.hjp-consulting.com:com.hjp.persosim.simulator.protocols.ca3
git clone git@git.hjp-consulting.com:com.hjp.persosim.simulator.protocols.ps
git clone git@git.hjp-consulting.com:com.hjp.poseidas
git clone git@git.hjp-consulting.com:de.persosim.driver.connector
git clone git@git.hjp-consulting.com:de.persosim.rcp
git clone git@git.hjp-consulting.com:de.persosim.simulator
git clone git@git.hjp-consulting.com:org.globaltester.cryptoprovider
git clone git@git.hjp-consulting.com:org.globaltester.logging
git clone git@git.hjp-consulting.com:org.globaltester.parent
